### ISSUE TITLE
Question: automate Azure Firewall rules configuration

### ISSUE THREAD

**Issue by tommysvensson0** [Azure/Azure-Network-Security#107]
Is there a way to handle firewall rules as a parameter from a parameter file? My scenario is that I would like users to request firewall openings and upon approval have a script modify a parameter file where it can either add or delete rules. I figured this would be an easier task then to have a script modify the whole firewall resource template. Thoughts?

Kind regards

**Comment by tobystic** [comment]
@tommysvensson0  Hi, Please see this [page](https://docs.microsoft.com/en-us/azure/firewall/deploy-rules-powershell#create-local-objects-of-the-firewall-policy-rule-collection-group-and-rule-collection) from Azure docs on how to pass parameters of a rule into a variable in Azure Firewall. I hope this helps with your question
