### ISSUE TITLE
Get-DanglingDnsRecords.ps1 outputs DNS names for resources that still exist

### ISSUE THREAD

**Issue by anonimitoraf** [Azure/Azure-Network-Security#14]
We found that this script returns DNS names for Classic VMs/Worker Roles, older stuff which we've confirmed still do exist

Can you guys please confirm this is the case?

**Comment by tobystic** [comment]
Adding @Arun-Mudiraj

**Comment by Arun-Mudiraj** [comment]
The script currently filters below resource types.. as creating Classic VMs is currently deprecated, could not test against classic VMs
Service | Type | Example
-- | -- | --
Azure Front Door | microsoft.network/frontdoors | abc .azurefd.net
Azure Blob Storage | microsoft.storage/storageaccounts | abc. blob.core.windows.net
Azure CDN | microsoft.cdn/profiles/endpoints | abc.azureedge.net
Public IP addresses | microsoft.network/publicipaddresses | abc.EastUs.cloudapp.azure.com
Azure Traffic Manager | microsoft.network/trafficmanagerprofiles | abc.trafficmanager.net
Azure Container Instance | microsoft.containerinstance/containergroups | abc.EastUs.azurecontainer.io
Azure API Management | microsoft.apimanagement/service | abc.azure-api.net
Azure App Service | microsoft.web/sites | abc.azurewebsites.net
Azure App Service - Slots | microsoft.web/sites/slots | abc-def.azurewebsites.net

**Comment by anonimitoraf** [comment]
Right, I see. I guess we can just exempt Classic resources in our cleanup procedures
