### ISSUE TITLE
Failed to create a 'Settings' from the text 'Assembly references and imported namespaces serialized as XML namespaces'.

### ISSUE THREAD

**Issue by kaletkamk** [Azure/Azure-Network-Security#15]
**Describe the bug**
D:\powershell\dns\Get-DanglingDnsRecords.ps1 : Failed to create a 'Settings' from the text 'Assembly references and imported namespaces serialized as XML namespaces'.
At line:1 char:1
+ ./Get-DanglingDnsRecords.ps1  -FetchDnsRecordsFromAzureSubscription - ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (:) [Get-DanglingDnsRecords.ps1], XamlObjectWriterException
    + FullyQualifiedErrorId : System.Xaml.XamlObjectWriterException,Get-DanglingDnsRecords.ps1

**Reproduce**
Try to run the command
Get-DanglingDnsRecords.ps1  -FetchDnsRecordsFromAzureSubscription
**Expected behavior**

**Comment by AzureDanglingDNS** [comment]
@kaletkamk ,Can you please try upgrading the Az module version greater than 4.3, if you are using previous version, seems to a bug with older version of Az module [https://github.com/Azure/azure-powershell/issues/11976](https://github.com/Azure/azure-powershell/issues/11976)  , In case it does not fix the issue.  Please share the following out you receive from the below 2 commands

1. $PSVersionTable
2. Get-Module -ListAvailable

**Comment by tobystic** [comment]
@kaletkamk Hello, Have you been able to try the above steps ?

**Comment by tobystic** [comment]
Closing out this issue due to inactivity . Please refer to this issue  Azure/azure-powershell#11976
