### ISSUE TITLE
Give a rough idea as to the costs of deploying this

### ISSUE THREAD

**Issue by duckfez** [Azure/Azure-Network-Security#18]
Currently deploying this for a class, using my personal Azure account.  I have concerns as to the cost that is going to be picked up from it.  It would be nice to know, for example, that this is going to cost me roughly $10 a day (or whatever it is) as well as the frighteningly shocking cost of the DDOS service option...

(Specific to the "Network Security Lab" template is where my concern lies)

**Comment by tobystic** [comment]
@duckfez Thank you for using the Azure Network Security lab environment. It depends on the resources in use but Azure DDOS protection service can be turned off during the deployment. This option brings about significant reduction in the cost and should only be used for a definite amount of time. The average pricing for this environment with DDOS turned off is between $17 to $28 and could be minimized further by shutting down the compute instances after usage
