### ISSUE TITLE
Cannot run scripts as-directed because they are not signed

### ISSUE THREAD

**Issue by Jehoel** [Azure/Azure-Network-Security#19]
**Describe the bug**

1. The documentation page at https://github.com/Azure/Azure-Network-Security/tree/master/Cross%20Product/Find%20Dangling%20DNS%20Records has instructions to download/clone the repo and then run the script in PowerShell.
2. By default, PowerShell on Windows will not run downloaded scripts unless they are signed. So I get the below error:

> PS C:\Users\Stuff\Find Dangling DNS Records> ./Get-DanglingDnsRecords.ps1
./Get-DanglingDnsRecords.ps1 : File `C:\Users\Stuff\Find Dangling DNS Records\Get-DanglingDnsRecords.ps1` cannot be loaded.
> **The file `C:\Users\Stuff\Find Dangling DNS Records\Get-DanglingDnsRecords.ps1` is not digitally signed. You cannot run this script on the current system.**

**Reproduce**

(See above)

**Expected behavior**

I expected this script, from Microsoft, no-less, to be signed and ready to execute without needing to jump through any hoops to appease the PowerShell security gods.

**Screenshots**
If applicable, add screenshots/images to help explain your problem.

**Environment- if applicable**

```
PS C:\Users\Stuff\Find Dangling DNS Records> Get-Host


Name             : ConsoleHost
Version          : 5.1.19041.546
InstanceId       : f53aa37d-e823-4130-a656-8b07844a1d45
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-GB
CurrentUICulture : en-US
PrivateData      : Microsoft.PowerShell.ConsoleHost+ConsoleColorProxy
DebuggerEnabled  : True
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace

```

**Desktop (please complete the following information if applicable):**

Windows 10 Pro for Workstations, version 2004.

**Logs- if applicable**

None
 
**Additional context**

None

**Comment by Arun-Mudiraj** [comment]
We have published the module to https://www.powershellgallery.com/packages/AzDanglingDomain which should resolve the issue.

**Comment by Jehoel** [comment]
@Arun-Mudiraj Thanks
