### ISSUE TITLE
Link is not working (404)

### ISSUE THREAD

**Issue by soelchma** [Azure/Azure-Network-Security#190]
**Describe the bug**
the link to the DDoS custom policy json is not working (404) (https://github.com/Azure/Azure-Network-Security/tree/master/Azure%20DDoS%20Protection/Azure%20Policy%20Definitions/Restrict%20creation%20of%20Azure%20DDoS%20Protection%20Standard%20Plans%20with%20Azure%20Policy)

This link is not working:
(https://github.com/Azure/Azure-Network-Security/blob/master/Azure%20DDoS%20Protection/Policy%20-%20DDOS%20Restrict%20creation%20of%20Azure%20DDoS%20Protection%20Standard%20Plans%20with%20Azure%20Policy/AzurePolicyRuleDenyDDoSPlan.json)

**Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots/images to help explain your problem.

**Environment- if applicable**
 - What version of CLI was used [Az –version]

**Desktop (please complete the following information if applicable):**

**Logs- if applicable**
 - If logs are available, please provide relevant snippets
 
**Additional context**

**Comment by tobystic** [comment]
@soelchma  Thanks for the feedback. This has been updated. Closing issue. Feel free to open if issue persists
