### ISSUE TITLE
Azure Firewall Workbook - Parsing bug

### ISSUE THREAD

**Issue by ms-sambell** [Azure/Azure-Network-Security#192]
**Describe the bug**
The Azure Firewall workbook parsing for unstructured logs isn't functioning for Application and Network rule queries. Leading to the dashboard providing incomplete information.

**Reproduce**
1. Load the Azure Firewall workbook.
2. Click on the Application tab.
3. Scroll down to the panel "All IP addresses events"
4. Look at the Action column

**Expected behavior**
The log data should be parsed correctly.

**Screenshots**
<img width="563" alt="MicrosoftTeams-image (8)" src="https://user-images.githubusercontent.com/93104336/194965336-a0a67934-38f6-4bf9-ada2-96e669a3755c.png">

**Comment by tobystic** [comment]
@ms-sambell Thank you for the contribution. This will be reviewed and updated
