### ISSUE TITLE
The script is not fetching any DNS records in my DNS Zone

### ISSUE THREAD

**Issue by harinarayanan-muthukumar** [Azure/Azure-Network-Security#203]
**Describe the bug**
When i run the script it fetches all my azure resources perfectly , but its not able to find any Azure DNS in my Subscriptions even though I have multiple DNS zones in my subscription

**Reproduce**
Run the Script as provided in the examples and its not fetching no DNS zone or records
**Expected behavior**
I except it to find all Azure DNS and DNS entires , compare and let me know if I have any dangling DNS entries lying around

![image](https://user-images.githubusercontent.com/103427336/203620368-24b907d2-a0f7-42cf-922a-fec790c20157.png)
![image](https://user-images.githubusercontent.com/103427336/203620421-339177e5-b6a9-4639-ad66-fc784bebbe0a.png)
![image](https://user-images.githubusercontent.com/103427336/203620580-801ff247-3cdf-4936-8360-462b03c5378f.png)

**Comment by tobystic** [comment]
@harinarayanan-muthukumar Thank you for this feedback. We are looking into this issue

**Comment by harinarayanan-muthukumar** [comment]
Hi , I tried the same with Powershell 7 and the script works like a charm . So i suppose its something with 5.1 or some module version . Cloding this issue as no issues was observed in powershell 7
