### ISSUE TITLE
Securing Virtual Hub with Basic SKU Azure Firewall

### ISSUE THREAD

**Issue by geckodesalpes** [Azure/Azure-Network-Security#224]
**Describe the bug**
When securing an existing virtual hub with Azure Firewall, it is possible to select the Basic SKU unit from the configurator, accepting basic policies, still in the same configurator. However, once created the firewall is showed and billed as a standard one.

**Reproduce**
From the Azure portal
1. Create a Basic tier Firewall policy form the Firewall manager (i.e. DenyAll)
2. Create a Virtual Wan and an unsecured Virtual HUB
4. In the Virtual HUB, under the **Security** menu, select **Azure Firewall and Firewall Manager**
5. Jump to the second tab **Azure Firewall**
6. Select **Basic (preview)** tier and select the policy created at step 1.
7. Jump to the **Review + Confirm** step and validate that the **Basic** tier has well being selected
8. Click **Create** and wait...
9. Go on the freshly provisioned firewall resource and notice that it is of "Standard" tier

**Expected behavior**
- In accordance with the billing documentation, it should not be possible to select "Basic" firewall tier to secure a Virtual HUB (Adapt Portal UI configurator mask + validation process).
OR
- If the configurator / validation process that is correct, a **Basic** firewall should be provisioned instead of a Standard one, and the pricing should appear as well in the pricing documentation

**Screenshots**
![image](https://user-images.githubusercontent.com/11677246/219875916-841708b5-8390-41ff-bb44-4cfe8f7a2f38.png)

**Environment- if applicable**
Azure Portal UI "Version: 11.48.5.1 (v11.48.0.1#9717ae6517.230204-0143) Signed"

**Desktop (please complete the following information if applicable):**

**Logs- if applicable**
 
**Additional context**

**Comment by tobystic** [comment]
@geckodesalpes Thank you for the feedback. This issue is currently being reviewed by the Azure firewall team. An update will be provided once its available.

**Comment by tobystic** [comment]
adding @gumoden for tracking
