### ISSUE TITLE
Documentation clarity

### ISSUE THREAD

**Issue by Tbohunek** [Azure/Azure-Network-Security#234]
**Describe the bug**
Hi, this Workbook looks awesome. I'm just confused with the Documentation.

> To use the Workbook with Resource Specific logs enabled, use the deployment button below.

In Firewall context, what does this mean? What's the difference between the two Workbooks?

>   When deploying via ARM Template, please make sure you know what Resource ID (Log Analytics Workspace) you're wanting to use.

Why do I need to know it? At least I don't see which Template parameter should take this value. The Workbook itself then has selectors for any Workspace in any Subscription.

Many thanks for clarification. :)

**Comment by Tbohunek** [comment]
Update: I've deployed both options, providing Workspace ID to parameter `Workbook Source Id` instead of default `Azure Monitor`. But I don't see difference in behavior between the two.
![image](https://user-images.githubusercontent.com/16520646/228554713-bc33c5eb-3a3e-4f48-9fe2-3ea7f34ad12f.png)

**Comment by tobystic** [comment]
> @Tbohunek Thank you for the feedback. Response will be provided in 3 business days concerning this issue about clarity

Please see more information about resource specific logs (vs All logs) in this [documentation](https://learn.microsoft.com/en-us/azure/firewall/firewall-structured-logs).
Closing issue, please feel free to open this again.
