### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by dmrellan** [Azure/Azure-Network-Security#235]
**Describe the bug**
What destination table do we need to select for Diagnostic Settings if we want to use Azure Firewall Workbook: "Azure diagnostic" option or "resource specific"?

**Comment by gumoden** [comment]
Hi @dmrellan you can use Resource Specific tables as destination. You will find the new json file (Azure Firewall_ResourceSpecific_Gallery.json) to deploy the workbook in our GitHub repository: https://github.com/Azure/Azure-Network-Security/tree/master/Azure%20Firewall/Workbook%20-%20Azure%20Firewall%20Monitor%20Workbook

This new workbook, supporting Resource Specific tables is not available in Microsoft Sentinel yet.

**Comment by tobystic** [comment]
Closing this feedback. Please feel free to open it again if you have any questions
