### ISSUE TITLE
DNS - Find Dangling DNS Records Error on run "Assembly with same name is already loaded"

### ISSUE THREAD

**Issue by WB-Sh** [Azure/Azure-Network-Security#242]
**Describe the bug**
The "**DNS - Find Dangling DNS Records**" script fails on first time run to scan subscriptions and produce a list of dangling CNAMEs. Script will run successfully in locally from my own machine.

**Reproduce**
Right after installing, importing, and then running the module as follows:
`Get-DanglingDnsRecords -FetchDnsRecordsFromAzureSubscription`
I see some progress and it seems to finish fetching subscriptions then begin processing subscriptions & DnsZones/DnsRecordSets
Before the command errors out with the following error message:
`Import-Module:                                                                                                          
Line |
  13 |  …                       Import-Module -name $module -Scope Local -Force
     |                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Assembly with same name is already loaded`

**Expected behavior**
Expected script to finish & produce report

**Screenshots**
![image](https://user-images.githubusercontent.com/22642446/235925269-86401324-da7b-4d5b-b5f3-81df7fcf386d.png)

**Environment- if applicable**
- Using the Cloud Shell within Azure
- New Cloud Shell being created/tested
- Installed latest version of module as of today
![image](https://user-images.githubusercontent.com/22642446/235924559-bdc6e10c-44ff-406f-8c30-1b57836a8cd7.png)

**Desktop (please complete the following information if applicable):**
N/A - Cloud Shell

**Comment by Alexis-Grant** [comment]
Just to add that I have had the same issue when trying to run this today
![image](https://github.com/Azure/Azure-Network-Security/assets/91332845/12289a84-344a-416b-b1d0-b2f51577ae98)

**Comment by drknite72** [comment]
Also adding that the issue is still there
![image](https://github.com/Azure/Azure-Network-Security/assets/9481694/a182075d-0865-4095-9ebe-300552803450)

Also it breaks my cloud shell until I restart it.
![image](https://github.com/Azure/Azure-Network-Security/assets/9481694/650c3568-85a9-47a1-9581-279bbe3682f1)

**Comment by abhijeetgaiha** [comment]
Does this happen only in the cloud shell?

**Comment by tobystic** [comment]
@drknite72 Did you experience this when not using Cloud shell?

**Comment by drknite72** [comment]
Have not tried in out of cloud shell. Just came back to the tool to see if it had been fixed and was going to try it locally in PS

**Comment by drknite72** [comment]
Update it seems to run just fine locally, the problem still happens when running it from cloud shell

**Comment by Kasra-G** [comment]
Found a workaround - Deleting the Az.Accounts module imported by this tool seems to let the tool run.

`rm -rf /home/<user>/.local/share/powershell/Modules`

**Comment by tobystic** [comment]
Closing this issue because a work around exist. Feedback received
