### ISSUE TITLE
Question about FQDN vs CNAME fields in Dangling DNS script

### ISSUE THREAD

**Issue by Gleland** [Azure/Azure-Network-Security#276]
Hi everyone,

At my company we've been reading up on Azure's recommendations for how to detect dangling DNS records, and came across this repository. I'm curious if there's a specific reason why the FQDN value is being assigned to the CNAME field for a given record set. [Here is one example](https://github.com/Azure/Azure-Network-Security/blob/32141bb734518d5ae51bed5f7ca824a01b04ab49/Cross%20Product/DNS%20-%20Find%20Dangling%20DNS%20Records/AzDanglingDomain/Export/Get-DanglingDnsRecords.ps1#L63), but it occurs in multiple places, including in [the final logic](https://github.com/Azure/Azure-Network-Security/blob/32141bb734518d5ae51bed5f7ca824a01b04ab49/Cross%20Product/DNS%20-%20Find%20Dangling%20DNS%20Records/AzDanglingDomain/Export/Get-DanglingDnsRecords.ps1#L506-L522) for determining if a given record is dangling or not. 

Thanks for your time!

**Comment by tobystic** [comment]
Hello @Gleland  
Thank you for the feedback. We are looking into this issue and we will provide a feedback shortly

**Comment by abhijeetgaiha** [comment]
@gleland The script scans only CNAME records in the zone. The CNAME field for a records is where the target for the CNAME record is populated. This is why that field is being read everywhere in the code.

**Comment by Gleland** [comment]
@abhijeetgaiha Thanks for the quick response! I'm not sure I understand:

1) If the CNAME record is the field being checked, why does the script rename it to `FQDN` in a fwe places?
2) Shouldn't the script actually be checking for the FQDN resource itself ([as mentioned in Azure's dangling record documentation](https://learn.microsoft.com/en-us/azure/security/fundamentals/subdomain-takeover))?

**Comment by abhijeetgaiha** [comment]
The script is doing exactly what you describe. 

Like I said, the CNAME field is where the _target_ of the CNAME record is stored, which would be the FQDN of the resource.

**Comment by Gleland** [comment]
Ah! @abhijeetgaiha Thank you! I understand now. The canonical name is indeed what the script is referencing when checking for resources. Thank you for clarifying this! For any future readers, these two pages helped me with some more background reading:

- https://en.wikipedia.org/wiki/CNAME_record#Details
- https://datatracker.ietf.org/doc/html/rfc2181#section-10.1.1

I'll close this, thank you for your help!

**Comment by abhijeetgaiha** [comment]
@gleland Glad to help!
