### ISSUE TITLE
Application rule log statistics

### ISSUE THREAD

**Issue by Ankojin** [Azure/Azure-Network-Security#29]
Hi ,

I have deployed "Workbook - Azure Firewall Monitor Workbook " . Application rule log statistics page is not showing any log statics.

I can see the log statistics for Network rule log statistics but not Application rule log statistics.

![image](https://user-images.githubusercontent.com/42596984/108213004-86159c00-7169-11eb-9868-dd642806f351.png)

**Comment by anthony-roman** [comment]
From the screenshot it seems you have not selected a workspace in the dropdowns in the top left corner of the workbook.

**Comment by Ankojin** [comment]
Hi Anthony,
Already have selected Workspace for workbook. I can see the analytics for Network Rule. 
![image](https://user-images.githubusercontent.com/42596984/108441660-89f00e00-7290-11eb-957a-15a6dc2ef5d5.png)

**Comment by tobystic** [comment]
> Hi Anthony,
> Already have selected Workspace for workbook. I can see the analytics for Network Rule.
> ![image](https://user-images.githubusercontent.com/42596984/108441660-89f00e00-7290-11eb-957a-15a6dc2ef5d5.png)



Hello Ankojin,

Are you still seeing this issue?
