### ISSUE TITLE
Failed The 'New-AzureStorageContext' command was found in the module 'Azure.Storage', but the module could not be loaded. For more information, run 'Import-Module Azure.Storage'. 

### ISSUE THREAD

**Issue by AllenOnAzure** [Azure/Azure-Network-Security#347]
When I run the script in my Automation Account, I keep getting the following failed message:

Failed
The 'New-AzureStorageContext' command was found in the module 'Azure.Storage', but the module could not be loaded. For more information, run 'Import-Module Azure.Storage'. 

![image](https://github.com/Azure/Azure-Network-Security/assets/128151824/699aaa1a-7c0d-4778-9da9-a295aa817323)
![fwerr01](https://github.com/Azure/Azure-Network-Security/assets/128151824/6563d475-7459-4e0e-8e76-1418270b5fca)

**Reproduce**
1. Create a new runbook and paste the script and Test pane

**Expected behavior**
The runbook is expected to run successfully.

**Screenshots**
If applicable, add screenshots/images to help explain your problem.

**Environment- if applicable**
 - What version of CLI was used [Az –version]

**Desktop (please complete the following information if applicable):**
Windows OS 11 

**Logs- if applicable**
 - If logs are available, please provide relevant snippets
 
**Additional context**

**Comment by shabaz-github** [comment]
@AllenOnAzure Hello, is this issue related to any of the artifact in this repository? Could you please be specific about the artificat here. Thanks

**Comment by shabaz-github** [comment]
Closing this issue as there is no response. Please submit an issue with clear details on which artifact this is related to
