### ISSUE TITLE
Failed to load "Find in Access/Firewall Log" in Workbook - AppGw WAF Triage Workbook

### ISSUE THREAD

**Issue by anrub** [Azure/Azure-Network-Security#350]
**Describe the bug**
If I click on "Find in Access Log" or "Find in Firewall log", I get an error message from the portal, see

<img width="793" alt="Screenshot 2024-02-07 at 15 17 44" src="https://github.com/Azure/Azure-Network-Security/assets/1221893/d5ce591b-a504-4425-80bc-9b6c77388d1f">

**Reproduce**

1. Select scope of the WAF Policy
2. Select Triage by Rule - Rules that got triggered
3. Select Host affected
4. Select Hosts and urls impacted by selected rule
5. Go to "Find in Access Log" in the "Requests on selected host and url"
8. See error

**Expected behavior**
Opening of  the Logs that match the selected host and url, rule combunation

**Desktop (please complete the following information if applicable):**
 - Mac, Edge 121.0.2277.98 arm64

**Comment by mskuratowski** [comment]
Unfortunately, I'm having the same problem. Also, I tried to deploy the workbook again and the result is the same.
