### ISSUE TITLE
Azure Firewall Workbook - garbage data

### ISSUE THREAD

**Issue by nosalan** [Azure/Azure-Network-Security#374]
**Describe the bug**
The `Network and Rule Hitcount (SUM)` and `Application Rule Hitcount (SUM)` data is pretty useless because the values on the Y axis is changing when time range is changed. Consider the comparison of charts from the last 24 hours vs the last 48 hours. 
The last 24 hours:
![image](https://github.com/Azure/Azure-Network-Security/assets/2273250/780f29e7-f2d1-4a7e-90d4-04b8d006ebef)

The last 48 hours:
![image](https://github.com/Azure/Azure-Network-Security/assets/2273250/e4cfad68-c0d8-4473-9416-c6eb0db05e6b)

Now compare the last 24 hours on both chart, they are inconsistent. One can see that the values on Y axis are increasing when time range is selected.
The chart seems to be aggregating values in some unknown time buckets making the values on the Y axis not understandable. The readings on the Y axis should be consistent for the given time period regardless of the time range selected.

**Comment by nosalan** [comment]
The issue is also being triggered by simple browser resize, please see this GIF:

![AzureWorkbookIssue](https://github.com/Azure/Azure-Network-Security/assets/2273250/99648225-aafb-43e0-8718-8d0ccf212670)

**Comment by shabaz-github** [comment]
@gumoden Hey Gustavo, could you please help take a look at this.

**Comment by shabaz-github** [comment]
@nosalan This is a built in Metric that is being used in the Firewall workbook, however if you want to define the time buckets, you can choose the Time Granularity parameter as shown in the below image to solve this. 
![image](https://github.com/user-attachments/assets/b8e0e791-423e-45c6-a0c4-03d0c19098e2)
