### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ameya-bakshi** [Azure/Azure-Network-Security#43]
I was able to execute successfully few month back but facing below issue now, would really appreciate any support.
I have csv file containing cname and fqdn. using cloudshell and getting error as below
Search-AzGraph: /home/ameya/.local/share/powershell/Modules/AzDanglingDomain/0.0.5/Export/Get-DanglingDnsRecords.ps1:144
..esources = (Search-AzGraph -Query $( -join ($query, ' | count'))).Cou... 
Value cannot be null. (Parameter 'source')

**Comment by sowilo-be** [comment]
I have exactly the same error. I tried on multiple computers. Also logged in as Azure administrator to the tenant and ran the script again via Powershell. Same message, line 144 value cannot be null

**Comment by Arun-Mudiraj** [comment]
We have pushed a new version 0.0.6 to fix this issue, can you please update and check if you still face this issue.

**Comment by sowilo-be** [comment]
I tried on two different machines. On one I even did connect-AzAccount before running Get-DanglingDnsRecords -FetchDnsRecordsFromAzureSubscription. Still looks like the same error after using V0.0.6
 
 
![DanglingDomain_ErrorLine144](https://user-images.githubusercontent.com/80890169/122406306-082f9900-cf81-11eb-99eb-e14fc087a13a.png)

**Comment by tobystic** [comment]
@sowilo-be  Are you still experiencing this issue after the 0.0.6 fix?

**Comment by tobystic** [comment]
Closing issue.
