### ISSUE TITLE
Linked Resource of LogAnalytics Workspace is not respected if you have access to multiple subscriptions

### ISSUE THREAD

**Issue by FrankCRoth** [Azure/Azure-Network-Security#45]
**Describe the bug**
If you have multiple subscriptions and deploy the template even though you specify an analytics workspace correctly the workbook is connected to your default subscription. However, the link is created correctly in the workbook as Linked Resource and even the JSON View is pointing to the correct resource

**Reproduce**
Deploy the Workbook to a different subscription and specify an analytics workspace with the correct value for the template

**Expected behavior**
The workbook is connected to the correct analytics workspace.

**Screenshots**
If applicable, add screenshots/images to help explain your problem.

**Environment- if applicable**
no CLI used. Deployed directly from GIT repository

**Desktop (please complete the following information if applicable):**
 - OS: Microsoft Windows
 - Browser Edge
 - Version 

**Logs- if applicable**
 - If logs are available, please provide relevant snippets
 
**Additional context**

**Comment by tobystic** [comment]
@FrankCRoth Thank you for the feedback. This is currently being reviewed.

**Comment by chboeh** [comment]
@FrankCRoth,

Just looking into this, which Workbook template specifically are you experiencing this issue with? This ticket doesn't have a reference of what repo you're deploying.
