### ISSUE TITLE
All DNS mapped to Azure API management DNS "azure-api.net" is showing as Dangling

### ISSUE THREAD

**Issue by vinayraj-vijayan** [Azure/Azure-Network-Security#7]
Please check for Azure API management DNS "azure-api.net" in the script "Get-DanglingDnsRecordsPsCore.ps1"

Even tho Custom DNS from the domain's DNS zone is mapped to a DNS CNAME record of an Azure API Management service i.e azure-api.net it is showing as dangling.

**Comment by AzureDanglingDNS** [comment]
Thanks for reporting this issue, this bug is fixed in PR #12
